run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - opuscc
    - opusccenc
  exclude-rules:
    - path: (opuscc|opusccenc)
      linters:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - typecheck
